import { HomePage } from "./pages/home/home";
import { HeaderPage } from "./pages/components/header/header";
import { SliderPage } from "./pages/components/slider/slider";
import { ServicesPage } from "./pages/components/services/services";
import { ShoppingCartPage } from "./pages/components/shopping-cart/shopping-cart";
import { FooterPage } from "./pages/components/footer/footer";
let homePage = new HomePage();
homePage.render();
var headerPage = new HeaderPage();
headerPage.render(".page__header");
var sliderPage = new SliderPage();
sliderPage.render(".page__content");
var servicesPage = new ServicesPage();
servicesPage.render(".page__content");
var shoppingCartPage = new ShoppingCartPage();
shoppingCartPage.render(".page__content");
var footerPage = new FooterPage();
footerPage.render(".page__footer");
